# Generated by Django 5.0.3 on 2024-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0002_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter_on_duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sitter_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
