# Generated by Django 5.0.4 on 2024-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0004_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailypay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_attended', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monthlypay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('days_attended', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
