# Generated by Django 5.0.4 on 2024-04-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0005_dailypay_monthlypay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='Surname',
            new_name='last_name',
        ),
    ]
