# Generated by Django 5.0.3 on 2024-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0006_rename_surname_baby_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
