# Generated by Django 5.0.3 on 2024-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0007_alter_record_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('number_of_babies_attended_to', models.IntegerField()),
                ('amount_per_baby', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
            ],
        ),
    ]
