# Generated by Django 5.0.3 on 2024-04-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0008_babyattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babyattendance',
            old_name='surname',
            new_name='last_name',
        ),
    ]
