# Generated by Django 5.0.3 on 2024-04-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0009_rename_surname_babyattendance_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BabyAttendance',
            new_name='Sitter_payment',
        ),
    ]
