# Generated by Django 5.0.3 on 2024-05-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0011_remove_assign_first_name_remove_assign_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='sitter_on_duty',
        ),
        migrations.AddField(
            model_name='assign',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assign',
            name='sitter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assign',
            name='baby_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
