# Generated by Django 5.0.3 on 2024-05-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0012_remove_assign_sitter_on_duty_assign_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='assign',
            name='sitter_number',
        ),
        migrations.AddField(
            model_name='assign',
            name='sitter_on_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ddms_app.sitter_on_duty'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='baby_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='ddms_app.arrival'),
        ),
    ]
