# Generated by Django 5.0.3 on 2024-05-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0013_remove_assign_first_name_remove_assign_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='sitter_assigned',
        ),
        migrations.RemoveField(
            model_name='monthlypay',
            name='days_attended',
        ),
    ]
