# Generated by Django 5.0.3 on 2024-05-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0016_alter_arrival_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_on_duty',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sitter_on_duty',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sitter_on_duty',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.record'),
        ),
    ]
