# Generated by Django 5.0.3 on 2024-05-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0017_remove_sitter_on_duty_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_payment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sitter_payment',
            name='last_name',
        ),
        migrations.AddField(
            model_name='sitter_payment',
            name='sitter_on_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.sitter_on_duty'),
        ),
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='sitter_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
