# Generated by Django 5.0.3 on 2024-05-06 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0019_remove_departure_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypay',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dailypay',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dailypay',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='dailypay',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.departure'),
        ),
    ]
