# Generated by Django 5.0.3 on 2024-05-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0020_remove_dailypay_first_name_remove_dailypay_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='ddms_app.arrival'),
        ),
    ]
