# Generated by Django 5.0.3 on 2024-05-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0022_remove_dailypay_shift_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter_on_duty',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
