# Generated by Django 5.0.3 on 2024-05-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0024_dollstal_dollpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
