# Generated by Django 5.0.3 on 2024-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0025_departure_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollpay',
            name='amount_bought',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dollstal',
            name='amount_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
