# Generated by Django 5.0.3 on 2024-05-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0026_dollpay_amount_bought_dollstal_amount_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dollpay',
            name='arrival',
        ),
    ]
