# Generated by Django 5.0.3 on 2024-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0028_dollpay_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollpay',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
