# Generated by Django 5.0.3 on 2024-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0031_remove_record_recommenders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='sitter_number',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
