# Generated by Django 5.0.3 on 2024-05-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0032_alter_sitter_on_duty_sitter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter_on_duty',
            name='sitter_number',
        ),
    ]
