# Generated by Django 5.0.3 on 2024-05-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0034_arrival_age_arrival_gender_arrival_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_person', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_issue', models.IntegerField(blank=True, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dollpays', to='ddms_app.procurement')),
            ],
        ),
    ]
