# Generated by Django 5.0.3 on 2024-07-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddms_app', '0036_alter_record_sitter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='baby_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='ddms_app.arrival'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='sitter_on_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ddms_app.sitter_on_duty'),
        ),
        migrations.AlterField(
            model_name='dailypay',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.departure'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='ddms_app.arrival'),
        ),
        migrations.AlterField(
            model_name='dollpay',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babydoll', to='ddms_app.arrival'),
        ),
        migrations.AlterField(
            model_name='dollpay',
            name='dollstal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dollpays', to='ddms_app.dollstal'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dollpays', to='ddms_app.procurement'),
        ),
        migrations.AlterField(
            model_name='monthlypay',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpays', to='ddms_app.departure'),
        ),
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.record'),
        ),
        migrations.AlterField(
            model_name='sitter_payment',
            name='sitter_on_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitters', to='ddms_app.sitter_on_duty'),
        ),
    ]
